[INCLUDES]
before = common.conf

[Definition]
_daemon = asterisk

failregex = ^.*SecurityEvent="(InvalidPassword|ChallengeResponseFailed|InvalidAccountID|FailedACL)".*RemoteAddress="IPV[46]/(?:UDP|TCP|TLS|WS|WSS)/<HOST>/.*"$
            ^.*Failed to authenticate.*from '<HOST>'.*$
            ^.*Registration from '.*' failed for '<HOST>'.*$

ignoreregex =
