CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS btree_gin;

CREATE ROLE asterisk LOGIN PASSWORD 'changeme';
CREATE ROLE app      LOGIN PASSWORD 'changeme';
CREATE ROLE report   LOGIN PASSWORD 'changeme';

CREATE DATABASE asterisk_cc OWNER asterisk;
\connect asterisk_cc

GRANT CONNECT ON DATABASE asterisk_cc TO app, report;
GRANT USAGE ON SCHEMA public TO app, report;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE ON TABLES TO app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT ON TABLES TO report;
