-- CSP skill queues (from Telephony Call list). Safe to re-run.
INSERT INTO queues (id, name, description, sla_seconds, wrapup_seconds) VALUES
  ( 1, 'angliyskaya',     'angliyskaya gruppa',    20, 10),
  ( 2, 'uzbekskaya',      'uzbekskaya gruppa',     20, 10),
  ( 3, 'crbt_taj',        'CRBT Taj',              20, 10),
  ( 4, 'testing_skill',   'testing Skill',         30, 10),
  ( 5, 'corporate_state', 'Corporate state',       30, 10),
  ( 6, 'ishodyashiye',    'Iskhodyashiye zvonki',  15, 10),
  ( 7, 'tajikskaya',      'Tajikskaya gruppa',     20, 10),
  ( 8, 'russkaya',        'Russkaya Gruppa',       20, 10),
  ( 9, 'registration_sim','registration sim',      30, 10),
  (10, 'navichok',        'Navichok',              20, 10),
  (11, 'navichok2',       'navichok2',             20, 10),
  (12, 'rukovoditeli',    'RUKOVODITELI',          15, 10),
  (13, 'tech',            'Tech',                  25, 10),
  (14, 'mtt_cc',          'MTT(Call-Centre)',      20, 10),
  (15, 'aiwa_mobile',     'Aiwa-Mobile',           20, 10),
  (16, 'crbt_rus',        'CRBT rus',              20, 10),
  (17, 'babilon_mobile',  'Babilon Mobile',        20, 10),
  (18, 'babilon_mobile1', 'BabilonMobile1',        20, 10),
  (19, 'babilon_mobile2', 'Babilon Mobile2',       20, 10),
  (21, 'mbtrus',          'MBTrus',                20, 10),
  (22, 'kassa',           'Kassa',                 20, 10),
  (23, 'zolotaya_korona', 'ZolotayaKorona',        20, 10),
  (24, 'mobi_tel',        'Mobi Tel',              20, 10),
  (25, 'dealer_bm',       'Dealer BM',             20, 10),
  (26, 'mr_avval',        'Mr AVVAL',              20, 10),
  (27, 'mbt_rus2',        'MBT rus2',              20, 10),
  (28, 'dealers',         'Dealers',               20, 10),
  (29, 'queue6262',       'Queue6262',             20, 10),
  (30, 'dispecher6464',   'Dispecher6464',         20, 10),
  (31, 'testing_number',  'Testing Number',        30, 10),
  (32, 'new_skill',       'New Skill',             30, 10),
  (33, 'ivr',             'IVR',                   30, 10),
  (34, 'mybabilon',       'MyBabilon',             20, 10),
  (35, 'volte',           'VOLTE',                 20, 10),
  (36, 'test_yuztek',     'Test Yuztek',           30, 10)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  sla_seconds = EXCLUDED.sla_seconds,
  wrapup_seconds = EXCLUDED.wrapup_seconds;
