apiVersion: 1
datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: 15s

  - name: Postgres-CC
    uid: postgres-cc
    type: postgres
    access: proxy
    url: postgres:5432
    user: report
    editable: false
    secureJsonData:
      password: changeme
    jsonData:
      database: asterisk_cc
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
