[Unit]
After=cc-asterisk-prestart.service cc-gsm-routes.service
Requires=cc-asterisk-prestart.service
Wants=cc-gsm-routes.service

[Service]
Type=simple
User=asterisk
Group=asterisk
ExecStart=/usr/sbin/asterisk -f -U asterisk -G asterisk
ExecReload=/usr/sbin/asterisk -rx 'core reload'
Restart=on-failure
RestartSec=4
LimitNOFILE=65536
