[global]
hostname=${PG_HOST}
port=${PG_PORT}
dbname=${PG_DB}
user=${PG_USER}
password=${PG_PASSWORD}
table=cdr
encoding=UTF-8
schema=public

;; Use adaptive ODBC instead if you want CUSTOM userfields per call.
