[global]
hostname=127.0.0.1
port=5433
dbname=asterisk_cc
user=asterisk
password=changeme
table=cdr
encoding=UTF-8
schema=public

;; Use adaptive ODBC instead if you want CUSTOM userfields per call.
