[general]

[default_bridge](!)
type=bridge
mixing_interval=20
internal_sample_rate=auto
record_conference=no
video_mode=none

[supervisor_bridge](default_bridge)
max_members=10

[user_default](!)
type=user
quiet=yes
announce_user_count=no
announce_only_user=no

[admin_user](user_default)
admin=yes
end_marked=yes
