[general]
dateformat=%F %T.%3q
queue_log=yes
queue_log_to_file=yes
queue_log_name=queue_log
exec_after_rotate=gzip -q9 ${filename}.${rotatecount}; /opt/cc/scripts/queue_log_rotate_hook.sh ${filename}

[logfiles]
console => notice,warning,error
messages => notice,warning,error
security => security
full => notice,warning,error,verbose,debug,dtmf,fax
