[general]
enabled=yes
port=5038
bindaddr=127.0.0.1
displayconnects=yes
authtimeout=30
authlimit=50

[cti]
secret=${ASTERISK_AMI_PASSWORD}
deny=0.0.0.0/0.0.0.0
permit=127.0.0.1/255.255.255.255
permit=10.0.0.0/255.0.0.0
read=system,call,log,verbose,command,agent,user,config,dtmf,cdr,dialplan,reporting,cc,security
write=system,call,agent,user,config,command,reporting,originate,cc

[exporter]
secret=${ASTERISK_AMI_PASSWORD}
deny=0.0.0.0/0.0.0.0
permit=127.0.0.1/255.255.255.255
read=system,call,reporting,cdr
write=
