[modules]
autoload=yes

noload => chan_sip.so
noload => app_voicemail.so
noload => cdr_csv.so
noload => cdr_manager.so
noload => cel_custom.so
noload => res_phoneprov.so
preload => res_srtp.so
load => codec_opus.so
