#!/usr/bin/env python3
"""
Синхронизация Postgres → Asterisk (queues, VDN dialplan, PJSIP agents).
Пишет *._generated.conf в /etc/asterisk и создаёт .reload_requested для entrypoint.
"""
from __future__ import annotations

import argparse
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

try:
    import psycopg2
    from psycopg2.extras import RealDictCursor
except ImportError:
    psycopg2 = None  # type: ignore

ASTERISK_ETC = Path(os.environ.get("CC_ASTERISK_ETC", "/etc/asterisk"))
QUEUES_FILE = ASTERISK_ETC / "queues_generated.conf"
VDN_FILE = ASTERISK_ETC / "vdn_generated.conf"
PJSIP_AGENTS_FILE = ASTERISK_ETC / "pjsip_agents.conf"
RELOAD_STAMP = ASTERISK_ETC / ".reload_requested"


def set_etc_paths(etc: Path) -> None:
    """Обновить пути к generated-конфигам (Web UI и CLI)."""
    global ASTERISK_ETC, QUEUES_FILE, VDN_FILE, PJSIP_AGENTS_FILE, RELOAD_STAMP
    ASTERISK_ETC = etc
    QUEUES_FILE = etc / "queues_generated.conf"
    VDN_FILE = etc / "vdn_generated.conf"
    PJSIP_AGENTS_FILE = etc / "pjsip_agents.conf"
    RELOAD_STAMP = etc / ".reload_requested"


PUBLIC_DOMAIN = os.environ.get("PUBLIC_DOMAIN", "172.16.6.183")

PJSIP_TPL = """; agent {sip}
[{sip}](agent-tpl)
type=endpoint
transport=transport-ws
auth={sip}-auth
aors={sip}
callerid={fullname} <{sip}>
from_domain={from_domain}

[{sip}](agent-aor-tpl)
type=aor

[{sip}-auth](agent-auth-tpl)
type=auth
username={sip}
password={password}
"""


def db_conn():
    if not psycopg2:
        raise RuntimeError("psycopg2 required")
    return psycopg2.connect(
        host=os.environ.get("PG_HOST", "127.0.0.1"),
        port=int(os.environ.get("PG_PORT", "5433")),
        dbname=os.environ.get("PG_DB", "asterisk_cc"),
        user=os.environ.get("PG_API_USER", os.environ.get("PG_USER", "postgres")),
        password=os.environ.get("PG_API_PASSWORD", os.environ.get("PG_PASSWORD", "changeme")),
    )


def esc_asterisk(s: str) -> str:
    return (s or "").replace("\\", "\\\\").replace('"', '\\"')


def generate_queues_conf(
    rows: list[dict], members_by_queue: dict[str, list[dict]] | None = None
) -> str:
    members_by_queue = members_by_queue or {}
    lines = [
        "; AUTO-GENERATED by cc_config_sync.py — do not edit",
        f"; {datetime.now(timezone.utc).isoformat()}",
        "",
    ]
    for r in rows:
        name = r["name"]
        sla = int(r.get("sla_seconds") or 20)
        wrap = int(r.get("wrapup_seconds") or 10)
        desc = r.get("description") or r.get("display_name") or name
        lines.append(f"; {desc}")
        lines.append(f"[{name}](queue-defaults)")
        lines.append(f"servicelevel={sla}")
        lines.append(f"wrapuptime={wrap}")
        members = members_by_queue.get(name, [])
        if not members:
            lines.append("; no active agents assigned (см. agent_queue)")
        for m in members:
            sip = str(m.get("sip_user") or "")
            if not re.match(r"^[0-9]+$", sip):
                continue
            penalty = int(m.get("penalty") or 0)
            lines.append(f"member => PJSIP/{sip},{penalty}")
        lines.append("")
    return "\n".join(lines) + "\n"


def generate_vdn_conf(routes: list[dict], options_by_vdn: dict[int, list[dict]]) -> str:
    lines = [
        "; AUTO-GENERATED VDN routes",
        f"; {datetime.now(timezone.utc).isoformat()}",
        "",
        "[vdn-route]",
    ]
    enabled = [r for r in routes if r.get("enabled", True)]

    for r in enabled:
        num = re.sub(r"\D", "", str(r["number"]))
        if not num:
            continue
        ctx = f"vdn-{num}"
        if r["route_type"] == "ivr_language":
            lines.append(f"exten => {num},1,Goto({ctx}-ivr,s,1)")
        else:
            lines.append(f"exten => {num},1,Goto({ctx}-direct,s,1)")
    lines.append("")
    lines.append("; fallback: неизвестный DID → общий IVR")
    lines.append("exten => _X.,1,Goto(ivr-main,s,1)")
    lines.append("")

    for r in enabled:
        if r["route_type"] == "ivr_language":
            continue
        num = re.sub(r"\D", "", str(r["number"]))
        if not num:
            continue
        ctx = f"vdn-{num}"
        q = r.get("queue_name") or "support"
        lines.append(f"[{ctx}-direct]")
        lines.append(f"exten => s,1,NoOp(VDN {esc_asterisk(r.get('name') or num)} direct -> {q})")
        lines.append(" same => n,AGI(/opt/cc/scripts/lookup_subscriber.agi,${CALLERID(num)})")
        lines.append(' same => n,GotoIf($["${SUB_BLOCKED}"="1"]?blacklisted,1)')
        lines.append(' same => n,GotoIf($["${SUB_VIP}"="1"]?queue-enter,${SUB_VIP_QUEUE},1)')
        lines.append(f" same => n,Goto(queue-enter,{q},1)")
        lines.append(" same => n,Hangup()")
        lines.append("")

    for r in enabled:
        if r["route_type"] != "ivr_language":
            continue
        num = re.sub(r"\D", "", str(r["number"]))
        if not num:
            continue
        ctx = f"vdn-{num}-ivr"
        opts = options_by_vdn.get(r["id"], [])
        lines.append(f"[{ctx}]")
        lines.append(f"exten => s,1,NoOp(VDN IVR {esc_asterisk(r.get('name') or num)})")
        lines.append(" same => n,Answer()")
        lines.append(" same => n,Wait(0.3)")
        lines.append(" same => n,Set(IVR_RETRIES=0)")
        lines.append(" same => n,AGI(/opt/cc/scripts/lookup_subscriber.agi,${CALLERID(num)})")
        lines.append(' same => n,GotoIf($["${SUB_BLOCKED}"="1"]?blacklisted,1)')
        lines.append(' same => n,GotoIf($["${SUB_VIP}"="1"]?queue-enter,${SUB_VIP_QUEUE},1)')
        lines.append(" same => n(menu),Read(IVR_DIGIT,,1,,,15)")
        for o in opts:
            digit = str(o.get("digit") or "")[:1]
            queue = o.get("queue_name") or "support"
            if digit:
                lines.append(
                    f' same => n,GotoIf($["${{IVR_DIGIT}}"="{digit}"]?queue-enter,{queue},1)'
                )
        lines.append(" same => n,Goto(ivr-main,timeout,1)")
        for o in opts:
            digit = str(o.get("digit") or "")[:1]
            queue = o.get("queue_name") or "support"
            if digit:
                lines.append(f"exten => {digit},1,Goto(queue-enter,{queue},1)")
        lines.append("exten => i,1,Goto(ivr-main,i,1)")
        lines.append("exten => t,1,Goto(ivr-main,t,1)")
        lines.append("")

    return "\n".join(lines) + "\n"


def generate_pjsip_agents(rows: list[dict]) -> str:
    lines = ["; AUTO-GENERATED PJSIP agents", ""]
    for r in rows:
        sip = r.get("sip_user") or ""
        if not re.match(r"^[0-9]+$", sip):
            continue
        pwd = r.get("sip_password") or ""
        full = r.get("full_name") or sip
        lines.append(
            PJSIP_TPL.format(
                sip=sip,
                fullname=esc_asterisk(full),
                password=pwd,
                from_domain=PUBLIC_DOMAIN,
            )
        )
    return "\n".join(lines) + "\n"


def fetch_all(conn) -> tuple[list, list, dict, list, dict]:
    with conn.cursor(cursor_factory=RealDictCursor) as cur:
        cur.execute(
            "SELECT name, description, display_name, sla_seconds, wrapup_seconds "
            "FROM queues ORDER BY id"
        )
        queues = cur.fetchall()
        cur.execute(
            "SELECT id, number, name, description, route_type, queue_name, enabled "
            "FROM vdn_routes ORDER BY id"
        )
        routes = cur.fetchall()
        cur.execute(
            "SELECT vdn_id, digit, lang, label, queue_name, skill_queue_id, sort_order "
            "FROM vdn_language_options ORDER BY vdn_id, sort_order, digit"
        )
        opts_rows = cur.fetchall()
        cur.execute(
            "SELECT sip_user, full_name, sip_password FROM agents "
            "WHERE status = 'active' AND sip_user ~ '^[0-9]+$' ORDER BY sip_user"
        )
        agents = cur.fetchall()
        cur.execute(
            "SELECT aq.queue, a.sip_user, aq.penalty "
            "FROM agent_queue aq JOIN agents a ON a.id = aq.agent_id "
            "WHERE a.status = 'active' AND a.sip_user ~ '^[0-9]+$' "
            "ORDER BY aq.queue, aq.penalty, a.sip_user"
        )
        member_rows = cur.fetchall()
    opts_by: dict[int, list] = {}
    for o in opts_rows:
        opts_by.setdefault(o["vdn_id"], []).append(o)
    members_by_queue: dict[str, list] = {}
    for m in member_rows:
        members_by_queue.setdefault(m["queue"], []).append(m)
    return queues, routes, opts_by, agents, members_by_queue


def write_files(queues, routes, opts_by, agents, members_by_queue) -> dict:
    ASTERISK_ETC.mkdir(parents=True, exist_ok=True)
    QUEUES_FILE.write_text(
        generate_queues_conf(queues, members_by_queue), encoding="utf-8"
    )
    VDN_FILE.write_text(generate_vdn_conf(routes, opts_by), encoding="utf-8")
    PJSIP_AGENTS_FILE.write_text(generate_pjsip_agents(agents), encoding="utf-8")
    RELOAD_STAMP.write_text(datetime.now(timezone.utc).isoformat(), encoding="utf-8")
    return {
        "queues": len(queues),
        "vdn_routes": len([r for r in routes if r.get("enabled", True)]),
        "pjsip_agents": len(agents),
        "queue_members": sum(len(v) for v in members_by_queue.values()),
        "etc": str(ASTERISK_ETC),
    }


def sync_all(request_reload: bool = True) -> dict:
    with db_conn() as conn:
        data = fetch_all(conn)
    stats = write_files(*data)
    stats["reload_requested"] = request_reload
    return stats


def apply_cli_reload() -> None:
    import subprocess

    for cmd in ("dialplan reload", "queue reload all", "pjsip reload"):
        subprocess.run(["asterisk", "-rx", cmd], check=False)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--etc",
        default=os.environ.get("CC_ASTERISK_ETC", "/etc/asterisk"),
        help="Asterisk etc directory for generated configs",
    )
    parser.add_argument("--no-reload", action="store_true")
    parser.add_argument("--reload-now", action="store_true", help="run asterisk -rx reloads in this container")
    args = parser.parse_args()
    set_etc_paths(Path(args.etc))

    stats = sync_all(request_reload=not args.no_reload)
    print(stats, flush=True)
    if args.reload_now:
        apply_cli_reload()
        RELOAD_STAMP.unlink(missing_ok=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
